FROM       ubuntu:18.04
#MAINTAINER subinghong

ENV LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LANGUAGE=en_US.UTF-8 \
    TAILSCALE_KEY=${TAILSCALE_KEY} \
    TAILSCALE_HOSTNAME=${TAILSCALE_HOSTNAME}

RUN apt-get update
RUN apt-get install -y openssh-server vim zip unzip git curl
RUN mkdir /var/run/sshd

RUN echo 'root:rootpw' |chpasswd
RUN useradd -m alpine  && echo "alpine:`uuidgen`" | /usr/sbin/chpasswd  && adduser alpine sudo
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
RUN echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
RUN mkdir /root/.ssh

RUN echo "#!/bin/bash" > start.sh
RUN chmod +x /start.sh

RUN echo "sh -c 'echo root:\${ROOT_PASSWORD:-rootpw} | chpasswd'" >> start.sh

#install nginx
RUN apt-get install -y nginx
RUN echo "nginx" >> start.sh

#add nginx gost proxy config
RUN mkdir -p /etc/nginx/sites-enabled/
RUN echo "" > /etc/nginx/sites-enabled/default
RUN mkdir -p /etc/nginx/conf.d/
RUN echo "map \$http_upgrade \$connection_upgrade {" > /etc/nginx/conf.d/default.conf
RUN echo "   default upgrade;" >> /etc/nginx/conf.d/default.conf
RUN echo "  '' close;" >> /etc/nginx/conf.d/default.conf
RUN echo "}" >> /etc/nginx/conf.d/default.conf
RUN echo "server {" >> /etc/nginx/conf.d/default.conf
RUN echo "  listen     80 default_server;" >> /etc/nginx/conf.d/default.conf
RUN echo "  listen     [::]:80 default_server;" >> /etc/nginx/conf.d/default.conf
RUN echo "  server_name  localhost;" >> /etc/nginx/conf.d/default.conf
RUN echo "  location / {" >> /etc/nginx/conf.d/default.conf
RUN echo "    root   /var/www/html;" >> /etc/nginx/conf.d/default.conf
RUN echo "    index  index.html index.htm index.nginx-debian.html;">>  /etc/nginx/conf.d/default.conf
RUN echo "  }" >> /etc/nginx/conf.d/default.conf
RUN echo "  location /vsc/ {" >> /etc/nginx/conf.d/default.conf
RUN echo "    proxy_pass http://127.0.0.1:8443/;" >> /etc/nginx/conf.d/default.conf
RUN echo "    proxy_set_header Host \$host;" >> /etc/nginx/conf.d/default.conf
RUN echo "    proxy_http_version 1.1;" >> /etc/nginx/conf.d/default.conf
RUN echo "    proxy_set_header Upgrade \$http_upgrade;" >> /etc/nginx/conf.d/default.conf
RUN echo "    proxy_set_header Connection \"upgrade\";" >> /etc/nginx/conf.d/default.conf
RUN echo "  }" >> /etc/nginx/conf.d/default.conf
RUN echo "}" >> /etc/nginx/conf.d/default.conf

#install code-server
RUN curl -fOL https://github.com/coder/code-server/releases/download/v4.4.0/code-server-4.4.0-linux-amd64.tar.gz
RUN tar --no-same-owner -xzvf code-server-4.4.0-linux-amd64.tar.gz
RUN rm code-server-4.4.0-linux-amd64.tar.gz
RUN echo "if [ -d code-server-4.4.0-linux-amd64 ]; then" >> start.sh
RUN echo "  cd code-server-4.4.0-linux-amd64" >> start.sh
RUN echo "  mkdir -p /mydata/vsc_user_data" >> start.sh
RUN echo "  if [ \$VSC_ENABLE ]; then" >> start.sh
RUN echo "  export PASSWORD=\${VSC_PASSWORD:-vscpw} && nohup ./bin/code-server --config vsc_config.yaml --bind-addr 0.0.0.0:8443 --auth password --user-data-dir /mydata/vsc_user_data & > nohup_code-server.out & echo $! > code-server.pid" >> start.sh
RUN echo "  fi" >> start.sh
RUN echo "fi" >> start.sh

RUN echo "/usr/sbin/sshd -D" >> start.sh

RUN echo "if [ -f /mydata/start_ext.sh ]; then . /mydata/start_ext.sh ; fi" >> start.sh


RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 22

ENTRYPOINT [ "/start.sh" ]
