openapi: "3.0.0"
info:
  title: Gost Service
  version: 1.0.0
paths:
  /gost:
    get:
      summary: Greet a Gost
      description: Greet a person by Gost
      tags:
        - Gost
      parameters:
        - name: name
          in: query
          description: Name of the person to greet
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
      deprecated: false
      security: []